# Access via "http://localhost:8091"
#   (or "http://$(docker-machine ip):8091" if using docker-machine)
#

version: '3.2'

services:

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task
        volumes:
            - mysqldatavolume:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - mysql
        restart: always
        ports:
            - 9090:80
        environment:
            PMA_HOST: mysql

    apache:
        build: .
        container_name: task
        volumes:
            - ./:/var/www/html
        ports:
            - 9080:80
        restart: always

volumes:
    mysqldatavolume:
